// Code generated by jsonschema.
// DO NOT EDIT!

package main

import "time"

type Album struct {
	CreatedAt    time.Time `json:"created_at"`
	DeletedAt    time.Time `json:"deleted_at"`
	ID           string    `json:"id"`
	LikedUserIds []int64   `json:"liked_user_ids"`
	Name         string    `json:"name"`
	Private      bool      `json:"private"`
	TaggedUsers  []User    `json:"tagged_users"`
	UpdatedAt    time.Time `json:"updated_at"`
	User         User      `json:"user"`
}

type User struct {
	Age        int64     `json:"age"`
	CreatedAt  time.Time `json:"created_at"`
	Email      string    `json:"email"`
	Icon       string    `json:"icon"`
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	ScreenName string    `json:"screen_name"`
	UpdatedAt  time.Time `json:"updated_at"`
}
