//DONOTEDIT this code is generated by jsonschema generate
package router

import (
	"time"

	"github.com/go-martini/martini"
)

var a string

func Route(r martini.Router) {
	r.AddRoute("POST", "/albums", CreateAlbum)
	r.AddRoute("GET", "/albums", ReadAlbums)
	r.AddRoute("GET", "/albums/:album_id", ReadAlbum)
	r.AddRoute("PATCH", "/albums/:album_id", UpdateAlbum)
	r.AddRoute("DELETE", "/albums/:album_id", DeleteAlbum)
	r.AddRoute("POST", "/albums/:album_id/files", CreateAttachment)
	r.AddRoute("POST", "/users", CreateUser)
	r.AddRoute("GET", "/users", ReadUsers)
	r.AddRoute("GET", "/users/:user_id", ReadUser)
	r.AddRoute("POST", "/users/:user_id/icons", CreateUser)
	r.AddRoute("DELETE", "/users/:user_id", DeleteUser)
}

type Album struct {
	CreatedAt    time.Time `json:"created_at"`
	DeletedAt    time.Time `json:"deleted_at"`
	ID           string    `json:"id"`
	LikedUserIds []int64   `json:"liked_user_ids"`
	Name         string    `json:"name"`
	Private      bool      `json:"private"`
	TaggedUsers  []User    `json:"tagged_users"`
	UpdatedAt    time.Time `json:"updated_at"`
	User         User      `json:"user"`
}

type User struct {
	CreatedAt  time.Time `json:"created_at"`
	Email      string    `json:"email"`
	Icon       string    `json:"icon"`
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	ScreenName string    `json:"screen_name"`
	UpdatedAt  time.Time `json:"updated_at"`
}
